version: "3.7"
services:
  app:
    container_name: docker-sandbox
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
